name: Generate and Deploy Folium Map

on:
  push:
    branches:
      - main  # Setzen Sie dies auf den Namen des Branches, auf dem Sie arbeiten

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install folium branca

      - name: Generate Map
        run: |
          python coordinates.py  # Ihr Python-Script, das die Karte generiert

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Der Ordner, in dem Ihre generierte HTML-Datei gespeichert ist

